name: Build and deploy .NET + React apps to Azure Web App - Taarafou

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-backend:
    name: 🔷 Build & publish backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore backend dependencies
        run: dotnet restore ./backend/Taarafou.Posts/Taarafou.Posts.csproj

      - name: Publish backend
        run: dotnet publish ./backend/Taarafou.Posts/Taarafou.Posts.csproj --configuration Release --output ./publish/backend

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-publish
          path: ./publish/backend

  build-frontend:
    name: 🟢 Install & build frontend
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ./frontend/build

  deploy:
    name: 🚀 Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend-publish
          path: ./publish/backend

      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: ./frontend/build

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy both apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: Taarafou
          package: |
            ./frontend/build
            ./publish/backend
