name: Build and deploy .NET + React apps to Azure Web App - Taarafou

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup .NET SDK and publish solution
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Build & publish .NET solution
        run: |
          dotnet restore ./Taarafou-App.sln
          dotnet publish ./Taarafou-App.sln -c Release -o publish

      # 3. Setup Node.js and build React frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install and build React frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # 4. Merge React build into publish/wwwroot
      - name: Merge React build into wwwroot
        run: |
          rm -rf publish/wwwroot
          mkdir -p publish/wwwroot
          cp -R frontend/build/* publish/wwwroot/

      # 5. Add web.config for static hosting and SPA routing
      - name: Add web.config for static hosting
        run: |
          cat > publish/wwwroot/web.config << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <staticContent>
      <mimeMap fileExtension=".json" mimeType="application/json" />
    </staticContent>
    <defaultDocument>
      <files>
        <clear />
        <add value="index.html" />
      </files>
    </defaultDocument>
    <rewrite>
      <rules>
        <rule name="SPA Routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
    </rewrite>
  </system.webServer>
</configuration>
EOF

      # 6. Zip the publish folder
      - name: Zip publish folder
        run: |
          cd publish
          zip -r ../app.zip .

      # 7. Deploy ZIP to Azure Web App (disable remote build)
      - name: Deploy ZIP to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'taarafou'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'app.zip'
          enable-oryx-build: false
