# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure:            https://github.com/Azure/actions

name: Build and deploy Taarafou .NET + React app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 7 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Restore & publish backend
        working-directory: backend/Taarafou.Posts
        run: |
          dotnet restore
          dotnet publish -c Release -o publish

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install & build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Deploy both backend & frontend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: Taarafou
          # this secret must contain the XML publish-profile you 
          # downloaded from Azure’s “Get Publish Profile”
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # you can list multiple packages (backend publish folder + frontend build)
          package: |
            backend/Taarafou.Posts/publish
            frontend/build
