name: Build and deploy .NET + React apps to Azure Web App - Taarafou

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Publish .NET API
      working-directory: ./backend
      run: |
        dotnet publish ./backend.sln \
          --configuration Release \
          --output ./publish

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install & build React client
      working-directory: ./frontend
      run: |
        npm ci
        npm run build
      # بعد البناء، سيتم خروجه في ./frontend/build

    - name: Merge API & client into wwwroot
      run: |
        mkdir -p backend/publish/wwwroot
        cp -R frontend/build/* backend/publish/wwwroot/

    - name: Zip publish output
      working-directory: ./backend/publish
      run: |
        zip -r ../../app.zip .

    - name: Deploy ZIP to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'taarafou'                                           # اسم التطبيق في أزور
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}   # السِرّ الموجود لديك
        package: 'app.zip'                                             # مسار الأرشيف الذي أنشأناه
        enable-oryx-build: false                                       # **تعطيل** البناء البعيد

