name: Build and deploy .NET + React apps to Azure Web App - Taarafou

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish .NET solution
        run: |
          dotnet publish ./backend/backend.sln \
            -c Release \
            -o ./publish

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install & build React client
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Merge client build into wwwroot
        run: |
          rm -rf ./publish/wwwroot
          mkdir -p ./publish/wwwroot
          mv ./frontend/build/* ./publish/wwwroot

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'taarafou'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish'
          enable-oryx-build: false
