name: Build and deploy .NET + React apps to Azure Web App - Taarafou

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your repo
      - uses: actions/checkout@v3

      # 2. Setup .NET SDK and publish backend
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish .NET backend
        run: |
          dotnet publish backend/backend.sln \
            --configuration Release \
            --output ./publish

      # 3. Setup Node.js and build React frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install & build React client
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # 4. Merge the React build into the publish folder
      - name: Merge client build into wwwroot
        run: |
          rm -rf ./publish/wwwroot
          mv ./frontend/build ./publish/wwwroot

      # 5. Deploy the combined package to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'taarafou'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
