name: Build and deploy .NET + React apps to Azure Web App - Taarafou

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1) سحب الكود
    - uses: actions/checkout@v3

    # 2) إعداد .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # 3) نشر API إلى مجلد publish
    - name: Publish .NET API
      run: |
        dotnet publish backend/backend.sln \
          -c Release \
          -o publish

    # 4) إعداد Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 5) بناء واجهة React
    - name: Build React client
      working-directory: frontend
      run: |
        npm ci
        npm run build

    # 6) دمج مجلّد البناء في wwwroot
    - name: Copy React build into publish/wwwroot
      run: |
        rm -rf publish/wwwroot
        mkdir -p publish/wwwroot
        cp -r frontend/build/* publish/wwwroot/

    # 7) نشر إلى Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: taarafou                        # تأكد أن هذا هو اسم تطبيق Azure App Service
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish
