# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure:      https://github.com/Azure/actions

name: Build and deploy .NET + React apps to Azure Web App - Taarafou

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      # 3) Restore, build & publish the backend
      - name: Restore & publish Backend
        run: |
          cd backend/Taarafou.Posts
          dotnet restore
          dotnet publish -c Release -o publish

      # 4) Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 5) Install & build the React frontend
      - name: Install & build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
          # Copy the built static files into the backend wwwroot
          rm -rf ../backend/Taarafou.Posts/publish/wwwroot
          mkdir -p ../backend/Taarafou.Posts/publish/wwwroot
          cp -r build/* ../backend/Taarafou.Posts/publish/wwwroot

      # 6) Deploy the combined output to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Taarafou'                       # تأكد أنّه يطابق اسم الـWeb App في البوابة
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend/Taarafou.Posts/publish
